export const CITIES = [
  'Bogotá',
  'Medellín',
  'Cali',
  'Barranquilla',
  'Cartagena',
  'Bucaramanga',
  'Pereira',
  'Manizales',
  'Santa Marta',
  'Cúcuta',
  'Ibagué',
  'Villavicencio',
];

export const ORGANIZATIONS = [
  'Universidad Nacional de Colombia',
  'Universidad de los Andes',
  'Pontificia Universidad Javeriana',
  'Universidad del Rosario',
  'Universidad de Antioquia',
  'EAFIT',
  'Escuela Colombiana de Ingeniería',
  'Universidad Externado',
  'Universidad de la Sabana',
  'Universidad Distrital',
  'Universidad Pedagógica Nacional',
  'ICESI',
  'Universidad del Norte',
  'Politécnico Grancolombiano',
  'SENA',
];

export const PROGRAMS = [
  'Ingeniería de Sistemas',
  'Ingeniería Industrial',
  'Administración de Empresas',
  'Medicina',
  'Derecho',
  'Psicología',
  'Contaduría Pública',
  'Economía',
  'Ingeniería Civil',
  'Arquitectura',
  'Diseño Gráfico',
  'Comunicación Social',
  'Biología',
  'Química',
  'Matemáticas',
  'Física',
  'Enfermería',
  'Trabajo Social',
];

export const INTERESTS = [
  'Matemáticas',
  'Física',
  'Química',
  'Biología',
  'Programación',
  'Inglés',
  'Español',
  'Historia',
  'Geografía',
  'Economía',
  'Estadística',
  'Cálculo',
  'Álgebra',
  'Música',
  'Arte',
  'Filosofía',
];
